travis:
  secure:
    BINSTAR_TOKEN: VfRpPzmyuAGTOBuFqhwnAvWePmsQzUvDFKhgcp2KbR7Mywj/oOcEBJeazH9l4nzPz4WlZaQGH4Xxh9ND2s+HTzl1xYaMYSSKbx3kieMt5/phAgV8bm3j4CdkpYTA1yu41s5dNQ3rDW2e2nf1KVFTJsUEGcp73hxB4kJ23g5TV6KJ3D3SlsxSM7fO6dqUKdfO8t/X9yQ2EvXlP2lh0DEhU+5Aruk4JC28uYpszXVnIbDMin/OHKK1klDYL/o2QVPaUc73KS3zD8gMbGS85xfDoI7wSaJ9e+xD2RuOETlms67lktxEPu0MlPSWteuE8lcAFZUWD9br7KBHihWcCPD3xE2mJ6RE4mTF2yXJ3dD7nHXZRkfhZCwjYSsJJAC8EGoWL4xM1PIQqtCmdJt5F5NUN0KsOv2UekKyt6aw/dbFM2Dmrjt2EP2zuMWk7sbYODmrHEqWLfs65al1dtGHpJ6LpCG7U2TvFIuAsuDo9gt12L/ksl1Ew1OE83qoWr6VYNUjDPTUdyJWJcvCsqCdrolMycyYaEXktIY0w4BXm2YlgYhvcn2puJ6SbdcW7DRfWyJvs1c1Z7qYEbXi6nCoCLJnUk4VdF5FiRuTwWwquKPXik8dw8CMCwbwr++1COO0L3rs0HlEzb/1qO82E7aB7Dd0//mIJ2byB1TZwNc6jPFy68A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
