travis:
  secure:
    BINSTAR_TOKEN: K2Vb6XmrCtkY4DnbrfmXeLtBnMOVCSrdeN8kJQwnzn6f3BS4ILyUMJssyF8RmVk8lwPIiscYDSS/FImkx70ehIq+XTDP0c7jNjloFwcAPzNx1L3ykHwH6CxqlhtYja5sTwqUXjR8slYYm/R5cZmgFDIv5GMNBKxjWusCTHyg4sNCvToTO80ih+DVCSzRjsUz9ildeQPf4Pj5LPqOazlIOaTePmtyU9B6jglX9B+RNB1ftRCl7jDGRVae2avBWvUmZxMwARUqt7GVRe6nrPZ2enR7WPxImQNLLSDWMFeL4iTE5goCxl3zSSHof/W2ibogxE6+ZXfOXKLe0wf5QMx3Hz7KX2yptRu2UVbjB1kwIeEAdlnramm3+JXNHmpYZtPdl0pf8NQHMhHEblYQ87PckAAk9Iuaa3KApBoiDAz4YN6lppqU5rCZ5hGxUj7OewcpD1AKHvWX3XsxrnGXeYwVenEAH6CekBYjG4lT95MFoVVbxC14mhDt1AYq+SZ5x94LPvEVZ9AeeRsJBAyb+TYPqfCzeLJdR9zbZ57lQSbTcowdWk7Sxcsj8VpKrVp2J+lcggwVRznffOGJzPEEQmctIrOET5b/b9wMBoFgtmroMxpUPU4HjomcZ/FHd7wx4MckMHoSD6YM6IFOUH26RuhyoKHI76ltRXhc8D4jBy9dOmM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
