travis:
  secure:
    BINSTAR_TOKEN: pKpb6+Br3TbHeG6JEJcTuDnHqiF3m0snMl4RmGusrSkXZKJ2Ef2+AEH7FrGB9oKEDW+yzH5YYo6smqm2czXoKAKtF3vqQDzrjRNM6uMJ7QKNcBO7bTTI0vFzKmendB5vY6SY08p8xCGuElE5ZHmPc+98upQ6Kdi0CJ9FnxKS2gHKyUTj2vCe81L7EudF7VGeztXPQHcDIRZiUGUghhyuAhpkYXGJ5rpUYlSZ+pMh+G9ezmH0qEEocsxf5WNO7Empu/dcYmHr3gQEl9NEkN+vr4CnTU3DPbb4uaFqfZY+Vsz1pQJjrknhxUpUR3X3bEAsemF8rzV6D3ssyG+/AmGai19fZgP/5sN1VAflaf70ymSgsJjiIUXzGOO5/puq/frnVONpihRvTmRRH7cAJv5V6R1/on2bosPs3Rwfx0cajGc4HUvUJradZjt/wCAHgPURLNA4eYDmLtfSb87NSczF9l7F8lcHk5egxICRJ0+kSeY8ze/q02wMPK5udWfyRnXnp0+O8+FThg3iOu/RLd+7VtGpvLz7GEsQBEGarycHNo9CeH+owWeF3CLIIxsoCCe9a67HIFJoQZ8TS3pO+5pkoYBJUrzXr1vZwaCaLq0J3mbJgLrrkaVu7/M8d+PI07B4TmPVnCqmZMT8UAGhugFiZBhXaIjgEYWZQvGputMqa/E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
